name: Healthcheck server

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  healthcheck_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          url: http://akiratoma-pokedex.herokuapp.com/health
          follow-redirect: no
          max-attempts: 3
          retry-delay: 5s
          retry-all: no
